<a href="https://colab.research.google.com/github/shengjiyang/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/LS_DS_421_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The "left-most" column of a neural network in which contains the feature data of whatever is being examined.
### Hidden Layer: Where the magic happens...the layers in a neural network between the Input Layer and Output layer where data is weighted and sigmoided (or ReLu'd if you prefer) prior to the network's producing final output layer values.
### Output Layer: The "right-most" column of a neural network where either the data has been processed and clustered, classified, or regressed.
### Neuron: A node in a neural network.
### Weight: A calculation which determines how much the value in a given node will contribute to the nodes it is connected to in the layer "to the right" of the given node in a neural network.
### Activation Function: The function which ultimately determines whether a neuron will fire or not and with what intensity.
### Node Map: A beutiful diagram which allows humans to be able to make sense of the interrelationships between different neurons and the features which they carry.
### Perceptron: An algorithm which allows for binary classification.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [93]:
import pandas as pd

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

print(df.shape)
df.head()

(4, 3)


x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [0]:
# Defining the sigmoid and sigmoid derivative functions

from math import e

def sigmoid(x):
  return (e**x) / (1 + e**(x))

# From the lecture notes:

def sigmoid_derivate(x):
  sx = sigmoid(x)
  return sx * (1-sx)

In [95]:
# Setting random weights
from numpy.random import seed, random

seed(84)
weights = 2 * random((3, 1)) - 1
weights

array([[-0.90791801],
       [-0.25951537],
       [-0.51536347]])

In [96]:
import numpy as np

row0 = df.iloc[0].values
row1 = df.iloc[1].values
row2 = df.iloc[2].values
row3 = df.iloc[3].values

inputs = np.array([row0, row1, row2, row3])

print("---"*2 +"Data"+ "---"*2)
print(inputs)

print("\n")

weighted_sum = np.dot(inputs, weights)
print("---"*2 +"Weighted Sum"+ "---"*2)
print(weighted_sum)

------Data------
[[0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 0]]


------Weighted Sum------
[[-0.51536347]
 [-1.42328148]
 [-0.77487883]
 [-1.16743338]]


In [97]:
# This is assuming bias=0
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.37393705],
       [0.19414767],
       [0.31542466],
       [0.23731923]])

In [98]:
output0 = df.iloc[0]["y"]
output1 = df.iloc[1]["y"]
output2 = df.iloc[2]["y"]
output3 = df.iloc[3]["y"]

correct_outputs = np.array([
                            [output0],
                            [output1],
                            [output2],
                            [output3]
])

correct_outputs

array([[1],
       [1],
       [1],
       [0]])

In [99]:
error = correct_outputs - activated_outputs
error

array([[ 0.62606295],
       [ 0.80585233],
       [ 0.68457534],
       [-0.23731923]])

In [100]:
adjustments = error * sigmoid_derivate(weighted_sum)

print("---"*3+"Adjustments"+"---"*3)
print(adjustments)
print("\n")
print("---"*3+"Original Weights"+"---"*3)
print(weights)

---------Adjustments---------
[[ 0.14656643]
 [ 0.1260791 ]
 [ 0.14782168]
 [-0.0429545 ]]


---------Original Weights---------
[[-0.90791801]
 [-0.25951537]
 [-0.51536347]]


In [129]:
weights += np.dot(inputs.T, adjustments)

print("---"*3 +"New Weights"+ "---"*3)
weights

---------New Weights---------


array([[-1.82073232],
       [-1.80515525],
       [ 5.70830763]])

In [132]:
# Resetting the weights
seed(84)
weights = 2 * random((3, 1)) - 1

for i in range(10000):
    weighted_sum = np.dot(inputs, weights)

    # Note that this assumes bias=0
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivate(weighted_sum)
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)
print("---"*5)
print("Error")
print(correct_outputs - activated_output)

Weights after training
[[-2.41171845]
 [-2.40881086]
 [ 7.490333  ]]
Output after training
[[0.99944181]
 [0.99380971]
 [0.99382757]
 [0.00799844]]
---------------
Error
[[ 0.00055819]
 [ 0.00619029]
 [ 0.00617243]
 [-0.00799844]]


In [133]:
# Now with a learning rate of 0.1

# It appears in this case that learning_rate=1 is the best choice for
# maximizing training accuracy, but this could easily lead to overfitting.
  
seed(84)
weights = 2 * random((3, 1)) - 1

for i in range(10000):
  weighted_sum = np.dot(inputs, weights)
  # Note that this assumes bias=0
  activated_output = sigmoid(weighted_sum)
  error = correct_outputs - activated_output
  adjustments = 0.1 *(error * sigmoid_derivate(weighted_sum))
  weights += np.dot(inputs.T, adjustments)
    
print("Learning Rate:", 0.1)
print("Output after training")
print(activated_output)
print("---"*5)
print("Error")
print(correct_outputs - activated_output)

Learning Rate: 0.1
Output after training
[[0.99669217]
 [0.97991454]
 [0.9802189 ]
 [0.02593761]]
---------------
Error
[[ 0.00330783]
 [ 0.02008546]
 [ 0.0197811 ]
 [-0.02593761]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [113]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')

print(diabetes.shape)
diabetes.head()

(768, 9)


Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [196]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
target = "Outcome"

X = diabetes[feats]
y = diabetes[target]

print(X.shape)
X.head()

(768, 8)


Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33

[5 rows x 8 columns]

In [212]:
# For this first run through, we will apply MinMaxScaler to the dataset

scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X.shape

(768, 8)

In [0]:
# X = X.flatten()
# X.shape

In [0]:
##### Update this Class #####

class Perceptron:
  
  def __init__(self, learn_rate=0.1, niter=10):
      self.niter = niter
      self.learn_rate = learn_rate
    
  def __sigmoid(self, x):
    return (e**x) / (1 + e**(x))
    
  def __sigmoid_derivative(self, x):
    sx = self.__sigmoid(x)
    return sx * (1-sx)

  def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = 2 * np.random((X.shape[1], 0)) - 1

    for i in range(self.niter):
      # Weighted sum of inputs / weights
      weighted_sum = np.dot(X, weights)

      # Activate!
      activated_output = self.__sigmoid(weighted_sum)

      # Cac error
      error = y - activated_output

      # Adjustments
      adjustments = error * self.__sigmoid_derivative(weighted_sum)
      adjustments = self.learn_rate * adjustments

      # Update the Weights
      weights += np.dot(X.T, adjustments)
      return weights


  def predict(self, X):
    """Return class label after unit step"""
    return None

In [211]:
perceptron = Perceptron()
weights = perceptron.fit(X, y)
weights

TypeError: ignored

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?